info:
  app:
    version: '@project.version@'

t2:
  orchestrator:
    url: ${T2_ORCHESTRATOR_URL}
  cart:
    url: ${T2_CART_URL}
  inventory:
    url: ${T2_INVENTORY_URL}
    reservationendpoint: ${T2_RESERVATION_ENDPOINT} 

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
    health:
      show-details: always
  metrics:
    tags:
      application: uibackend
    distribution:
      percentiles:
        all: 0.5, 0.75, 0.95, 0.98, 0.99, 0.999, 1.0
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

opentracing:
  jaeger:
    service-name: uibackend
    enabled: ${T2_JAEGER_ENABLED}
    udp-sender:
      host: ${T2_JAEGER_HOST}
